server:
  port : 8080

spring:
  data:
    redis:
      host: linkey.co.kr
      port: 30379

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://linkey.co.kr:30432/linkey  #mydatabase
    username: linkeyadmin #myuser
    password: linkeyadmin12! #mypassword
    driver-class-name: org.postgresql.Driver
  graphql:
    graphiql:
      enabled: true
#    printer:
#      enabled: true
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST"
      allowed-headers: "*"
    schema:
      locations: classpath:static/graphql/
    playground:
      settings:
        request.credentials: "omit"

logging:
  level:
    org.springframework.graphql: DEBUG
    org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    root: trace


#datasource:
#  url: jdbc:postgresql://host.docker.internal:5432/mydatabase