name: Backend Dev CI/CD - Build and Deploy to Dev Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./spring-backend
    steps:
      # Spring Backend 리포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # Java 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      # SHA 앞 7자 추출
      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./spring-backend  # spring-backend 디렉토리로 설정
          file: ./spring-backend/Dockerfile  # 정확한 Dockerfile 경로
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app:${{ steps.vars.outputs.sha_short }}

      # Linkey-infra 리포지토리 체크아웃
      - name: Checkout Linkey-infra repo
        uses: actions/checkout@v4
        with:
          repository: Seollal-TF-TEAM/Linkey-infra
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # GitHub 토큰 필요
          path: linkey-infra

      # spring-boot/deployment.yaml 업데이트
      - name: Update image tag in deployment
        working-directory: ./linkey-infra
        run: |
          yq eval '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-app:${{ steps.vars.outputs.sha_short }}"' -i spring-boot/deployment.yaml

      # 변경 사항 커밋 및 푸시
      - name: Commit and push manifest changes
        working-directory: ./linkey-infra
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add spring-boot/deployment.yaml
          git commit -m "feat : [GitHub Actions] Update spring-boot-app image tag to ${{ steps.vars.outputs.sha_short }}"
          git push